apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-idle-exporter
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-idle-exporter
  namespace: default
  labels:
    app: gpu-idle-exporter
spec:
  selector:
    matchLabels:
      app: gpu-idle-exporter
  template:
    metadata:
      labels:
        app: gpu-idle-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9835"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            # GKE-specific label. For other providers, replace with the appropriate label:
            #   Amazon EKS:  k8s.amazonaws.com/accelerator: nvidia-gpu
            #   Generic:     nvidia.com/gpu.present: "true"
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      hostPID: true  # Required for per-process GPU metrics (driver >= 535.113.01)
      serviceAccountName: gpu-idle-exporter
      containers:
      - name: exporter
        image: ghcr.io/affinode/gpu-idle-exporter:latest
        imagePullPolicy: Always
        env:
        - name: POLL_INTERVAL
          value: "5s"
        - name: HTTP_PORT
          value: "9835"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/nvidia/lib64"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 9835
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9835
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9835
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: nvidia-lib
          mountPath: /usr/local/nvidia/lib64
          readOnly: true
        - name: host-dev
          mountPath: /dev
        - name: host-proc
          mountPath: /proc
          readOnly: true
      volumes:
      - name: nvidia-lib
        hostPath:
          # GKE-specific path. Other distros may use:
          #   /usr/lib/x86_64-linux-gnu/  (Ubuntu/Debian)
          #   /usr/local/nvidia/lib64/    (some CUDA base images)
          path: /home/kubernetes/bin/nvidia/lib64
          type: Directory
      - name: host-dev
        hostPath:
          path: /dev
          type: Directory
      - name: host-proc
        hostPath:
          path: /proc
          type: Directory
